### ISSUE TITLE
Tutorial is great, just one hiccup with older tag code

### ISSUE THREAD

**Issue by tomjohnson1492** [nanoc/nanoc.ws#77]
I loved the getting started tutorial. Everything was smooth sailing until this part:

Next, create a lib/tags.rb file and put in the following function:

```
def tags
  if @item[:tags].nil?
    '(none)'
  else
    @item[:tags].join(', ')
  end
end
```

Modify the layout and add a paragraph that outputs the tags:

```
<p>Tags: <%= tags %></p>
```

This appears [on this page](http://nanoc.ws/docs/tutorial/). 

I kept getting errors. I undid these edits and moved onto the next section: "Use a predefined helper"

This new helper method worked flawlessly. Maybe there's something wrong or incompatible with the old tag section?

**Comment by bobthecow** [comment]
what kind of errors?

**Comment by tomjohnson1492** [comment]
Looked like this:

```
Captain! We’ve been hit!

Message:

NameError: undefined local variable or method `tags' for #<Nanoc::Context:0x007fa70b97a608>

Compilation stack:

  - [item]   /about/ (rep default)

Stack trace:

  0. layout /default/:18:in `get_binding'
  1. /Users/tjohnson/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/erb.rb:849:in `eval'
  2. /Users/tjohnson/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/erb.rb:849:in `result'
  3. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/filters/erb.rb:34:in `run'
  4. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/base/compilation/filter.rb:121:in `setup_and_run'
  5. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/base/result_data/item_rep.rb:404:in `layout'
  6. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/base/compilation/item_rep_proxy.rb:69:in `layout'
  7. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/base/compilation/rule_context.rb:74:in `layout'
  8. /Users/tjohnson/projects/nanoc-tutorial/Rules:26:in `block in parse'
  9. /Users/tjohnson/.rvm/gems/ruby-2.0.0-p481/gems/nanoc-3.7.4/lib/nanoc/base/compilation/rule.rb:70:in `instance_eval'
  ... 31 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-
```

**Comment by ddfreyne** [comment]
@tomjohnson1492 The `undefined local variable or method 'tags'` error means nanoc can’t find the `tags` method definition somewhere in `lib/`. Can you verify that the `lib/tags.rb` you created is inside the `lib` directory inside the nanoc site?

**Comment by ddfreyne** [comment]
@tomjohnson1492 Is this still an issue for you? I’ll close this for now, as I can’t reproduce it, but do comment if the issue persists.
